apiVersion: skaffold/v2beta24
kind: Config
deploy:
  kubectl:
    manifests:
      - ./config/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: equationalapplications/birdsquawk
      context: BirdSquawks-Service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: equationalapplications/peep
      context: Peeps-Service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: equationalapplications/query
      context: Query-Service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: equationalapplications/front-end
      context: front-end
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .